### ISSUE TITLE
Documentation!

### ISSUE THREAD

**Issue by TomDonoghue** [wdfox/Confidence_Scanner#2]
I suggest adding a bit more documentation! Writing documentation as you write the code is (I think at least) way easier that going back to write it in later. Even for functions that seems very straight-forward, I recommend documenting them fully - it's crazy how quickly (I at least) forget the logic / specifics of code, and it's way quicker to read docs than the code itself. 

I suggest numpy docs (https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt), which is the same as is used in ERP-SCANR (and all of my code, when I'm being good). 

Part of the reason I point this out is that it makes it much easier for me (or for anyone reviewing code they didn't write) to eyeball quick issues if you've written out, for example, what types you expect all the inputs and outputs to be, I'm more likely to be able to notice if things look slightly funky.

(Also - writing docs is good practice for learning real programming!)

**Comment by wdfox** [comment]
@TomDonoghue - Thanks for the recommendation. I had been meaning to get to this for a while but wasn't exactly sure how to go about it. The link helped a lot. Fully documented now.
